spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=AdventureWorksLT_Data
    username: your-username
    password: your-password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

openshift:
  deployment:
    name: gridview
    namespace: your-namespace
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
